### ISSUE TITLE
(crates.io) "Plugin failed to decode" with nushell 0.90.1

### ISSUE THREAD

**Issue by LeoniePhiline** [fmotalleb/nu_plugin_desktop_notifications#3]
Hi!

This plugin unfortunately does not work with the current nushell:

```
~> notify -t "test notification body" --summary "test title"
Error:   × Plugin failed to decode
  help: array had incorrect length, expected 3
```

**Comment by fmotalleb** [comment]
Have you tried updating the plugin?

**Comment by LeoniePhiline** [comment]
It’s the latest from crates.io.

**Comment by fmotalleb** [comment]
They are updated now.
But since I don't update my crates often, the recommended approach would be to clone the repository and build the plugin from the source code. You can also consider using [`nupm`](https://github.com/nushell/nupm) to install plugins, especially those that require build time configuration. (for example clipboard plugin has custom `nupm` install script)
